### ISSUE TITLE
Consignas para todos

### ISSUE THREAD

**Issue by FedeBirge** [EMTSTISPC/Grupo1#3]
Consignas particulares para todos:

- Hay 3 archivos Word en la carpeta Proyecto 2 para desarrollar los temas,
  los tres están cargados con los títulos y subtítulos a desarrollar por cada uno( se irán creando las 
issues y asignando),
  para mejor comprensión. En la revisión final los cargaremos como PDF.
- Formato a usar en el documento(ya están con margen estrecho):
	Fuente: Arial Unicode MS
		Titulo: tamaño 14 en negrita. Alineación centrada.
		Subtitulo: tamaño 12 negrita. Alineación justificada.
		Desarrollo: tamaño 11. Alineación justificada.
- Otras consideraciones:
	-Al traducirse automáticamente el contenido se generan inconsistencias,
	por favor leer y darle sentido la texto, de paso nos aprendemos el contenido.
	y colaborar con el formato please.
NOTA importante: debemos trabajar haciendo ramas(branch) para luego unir todo,
ES IMPORTANTE QUE ASIMILEMOS LOS CONOCIMIENTOS DE GIT Y GITHUB

**Comment by GiseRomero** [comment]
Bueno, Fede entendido, gracias por hacer esto

**Comment by Emygut** [comment]
Hola a Todos. Fede comprendido, gracias por haber organizado.

**Comment by Domi74** [comment]
buen dia que se tiene que hacer estuve con finales y ahora bueno me pondre a hacer y ayudar al grupo

**Comment by Emygut** [comment]
Hola, Buen Dia. Ya cargue en el documento word la Descripción de los Modos
de funcionamiento de AVR ADC, Modo diferencial AVR ADC, Modo de reducción
de ruido AVR ADC. Cualquier novedad me avisan que faltaría.

**Comment by marlufer** [comment]
Hola a todos. Repasando que han hecho chicos, poniendome al dia
