### ISSUE TITLE
Ejer 2 - 1. Explicar detalladamente el funcionamiento del terminal virtual en proteus, del  monitor serie en VsCode@platformIO y del monitor serie en el ide de Arduino.

### ISSUE THREAD

**Issue by FedeBirge** [EMTSTISPC/Grupo1#41]

**Comment by Emygut** [comment]
Emygut asigno a Emygut

**Comment by gonaiot** [comment]
Que tal @Emygut el desarrollo esta incompleto ya que no explica propiamente el monitor serie de platformIO, ni de Arduino IDE; aun asi pudo participar y colaborar en la modificacion del flujo principal. Continue asi, y mejore el desarrollo de sus futuras producciones en cuanto a lo requerido. Saludos.
