### ISSUE TITLE
Ejer 2 - 5. Explique las propiedades avanzadas del terminal virtual.

### ISSUE THREAD

**Issue by FedeBirge** [EMTSTISPC/Grupo1#45]

**Comment by gonaiot** [comment]
@GiseRomero y @LitoCarunchio esta bien su asignacion colaborativa a este ejercicio, ya que eso depende del contexto. Aun asi, la respuesta a las propiedades avanzadas del terminal virtual de proteus esta incompleta. Pero lograron participar y proponer los cambios necesarios en el flujo principal. Continuen asi.
