### ISSUE TITLE
Ejer 2 - 6. Como funciona COMPIM y para que sirve? Que es un virtualizador de puertos,  de ejemplos de los mas utilizados.

### ISSUE THREAD

**Issue by FedeBirge** [EMTSTISPC/Grupo1#46]

**Comment by gonaiot** [comment]
@GiseRomero y @LitoCarunchio esta bien la reseña, aunque parcilamente incompleta. Pero en estas instancias se valora mas el hecho de su participacion grupal. Continuen mejorando.

**Comment by LitoCarunchio** [comment]
Hola buenos dias! Gracias profe por la valoración, lo tendré el cuenta para
la proxima tarea. Saludos
